export const tableSelectors = {
  searchInput: 'input[name="search"]',
  resetButton: 'button[data-name="reset"]',
  sortByDate: '[data-name="sortByDate"]',
  sortByTotal: '[data-name="sortByTotal"]',
  headerColumns: '.header-row .table-column',
  filterDate: 'input[name="date"]',
  filterCustomer: 'input[name="customer"]',
  filterSeller: 'select[name="seller"]',
  filterTotalFrom: 'input[name="totalFrom"]',
  filterTotalTo: 'input[name="totalTo"]',
  firstPage: 'button[name="first"]',
  prevPage: 'button[name="prev"]',
  nextPage: 'button[name="next"]',
  lastPage: 'button[name="last"]',
  page: 'input[name="page"]',
  rowsPerPage: 'select[name="rowsPerPage"]',
  rows: '[data-name="rows"] > .table-row',
  fromRow: '[data-name="fromRow"]',
  toRow: '[data-name="toRow"]',
  totalRows: '[data-name="totalRows"]',
} as const;